# PRINT HELLO WORLD

print("HELLO WORLD!")

# ADD 2 NUMBERS
X=10
Y=20
print(X+Y)

#COMMENTS STATEMENT

#(HASH) IT IS USED FOR SINGLE LINE COMMENT
"""TRIPLE QUOTES
THEY ARE USED FOR 
MULTI-LINE COMMENT"""

# PRINT STATEMENTS
# print("HELLO")
# print("WORLD")
# FOR NOT ADDING NEW LINE
# print("HELLO", end=",")
# print("WORLD")

